adding readme content
pl-fe-may23-codecreators/product-catalog pull request #20
Opened 2023-11-01 00:49 UTC by PawelP2001

## Click Up Task Link ⏰

[Infrastructure] Add Readme files to both repositories([Paste here link to ClickUp task](https://app.clickup.com/t/869317atw))

## What has been done 😄

I have added content to the README file, allowing visitors to get to know how to get started while working with the project

2023-11-01 09:33 UTC, klaudia-klis requested changes
You only wrote about very technical things. I would personally add something more about the project itself. First of all, what is it? How does it work? What can you do on our website?
I would start with the short description of our project.
## Product catalog website (or however we want to call it)
This website is this and this and does that and that...
## Features
Here I would describe shopping cart, that you can add products to your favorites etc
## DEMO
Demo link to our page! That's important
## Getting started
Here I would paste what you wrote, maybe don't use /##/ for writing commands, I think .md files have something what starts with backtick? You can Google that, and then the command looks like command, not like header.
## Technologies used
Also important

2023-11-01 09:41 UTC, klaudia-klis requested changes

2023-11-01 09:41 UTC, klaudia-klis commented on README.md
> +In the project directory, you can run:
But how can I get the project directory? I think you should mention git clone https:.. command

2023-11-05 00:57 UTC, emil-owczarek submitted a review, later dismissed
@PawelP2001 waiting for updates :dancing_men:

2023-11-09 17:50 UTC, klaudia-klis approved these changes

2023-11-09 17:54 UTC, merged